# Generated by Django 4.2.7 on 2024-06-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_nonregesteredclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonregesteredclient',
            name='comeback_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
