# Generated by Django 4.2.7 on 2024-08-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonregesteredclient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
