# Generated by Django 5.0.4 on 2024-04-27 18:28

import receipt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptcollector',
            name='id_collection',
        ),
        migrations.RemoveField(
            model_name='receiptcollector',
            name='receipt',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id',
            field=models.CharField(default=receipt.models.generate_random_sequence, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ReceiptID',
        ),
        migrations.DeleteModel(
            name='ReceiptCollector',
        ),
    ]
