# Generated by Django 5.0.4 on 2024-04-29 10:41

import receipt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_remove_receiptcollector_id_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='downlowdedReceipts',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='expireedReceipts',
        ),
        migrations.AddField(
            model_name='receipt',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='ShopReceipt',
            fields=[
                ('downlowdedReceipts', models.IntegerField(default=0)),
                ('expireedReceipts', models.IntegerField(default=0)),
                ('id', models.CharField(default=receipt.models.generate_random_sequence, max_length=10, primary_key=True, serialize=False)),
                ('expiredateValue', models.ManyToManyField(to='receipt.receipt')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
            },
        ),
    ]
