# Generated by Django 4.2.7 on 2024-08-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_shippingmethod_validnonorder_validorder_and_more'),
        ('receipt', '0003_remove_receipt_downlowdedreceipts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='id',
            new_name='receipt_reference',
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.validorder'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('sent', 'Sent'), ('expired', 'Expired')], default='issued', max_length=10),
        ),
        migrations.CreateModel(
            name='ReceiptItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('tax', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.validorderitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt.receipt')),
            ],
            options={
                'verbose_name': 'Receipt Item',
                'verbose_name_plural': 'Receipt Items',
            },
        ),
    ]
