# Generated by Django 4.2.7 on 2024-09-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0005_alter_shopreceipt_options_receipt_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='expiredateValue',
            field=models.CharField(default='', max_length=30),
        ),
    ]
