# Generated by Django 4.2.7 on 2024-06-11 18:58

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCategoryC', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCategoryP', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Image', models.ImageField(blank=True, null=True, upload_to=product.models.get_image_filename, verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, help_text='The order in which the images will be displayed')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=20, null=True, unique=True)),
                ('ProductName', models.CharField(max_length=255)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ProductSKU', models.CharField(max_length=50)),
                ('ProductDescription', models.TextField(blank=True)),
                ('available_from', models.DateField()),
                ('available_until', models.DateField()),
                ('quantity', models.IntegerField()),
                ('headding', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=False)),
                ('original', models.BooleanField(default=False)),
                ('gifted', models.BooleanField(default=False)),
                ('ProductCategoriesChild', models.ManyToManyField(related_name='child_category', through='product.ProductCategory', to='product.productcategorychild')),
                ('ProductCategoriesParent', models.ManyToManyField(related_name='parent_category', through='product.ProductCategory', to='product.productcategoryparent')),
                ('ProductImages', models.ManyToManyField(related_name='images', to='product.productimage')),
            ],
        ),
        migrations.CreateModel(
            name='SIZE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_value', models.TextField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('New', models.BooleanField(default=True)),
                ('Limited', models.BooleanField(default=True)),
                ('Ondemand', models.BooleanField(default=True)),
                ('Viral', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
                ('product_tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.tags')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.size')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='ProductTagsList',
            field=models.ManyToManyField(related_name='products', through='product.ProductTags', to='product.tags'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='colors',
            field=models.ManyToManyField(related_name='products', through='product.ProductColor', to='product.color'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='product.productmodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='reviews',
            field=models.ManyToManyField(related_name='product_reviews', to='product.productreview'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='size',
            field=models.ManyToManyField(related_name='product_size', through='product.ProductSize', to='product.size'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productmodel'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.color'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcategoryparent'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcategorychild'),
        ),
    ]
