# Generated by Django 4.2.7 on 2024-06-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategoryparent',
            name='ProductCategoryP',
            field=models.CharField(choices=[('Top', 'Top'), ('Down', 'Down'), ('Feet', 'Feet')], max_length=10),
        ),
    ]
