# Generated by Django 4.2.7 on 2024-06-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productcategoryparent_productcategoryp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategoryparent',
            name='ProductCategoryP',
            field=models.CharField(choices=[('Top', 'Top'), ('Down', 'Down'), ('Feet', 'Feet')], max_length=10, unique=True),
        ),
    ]
