# Generated by Django 4.2.7 on 2024-06-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcategoryparent_productcategoryp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Color_Siz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_sizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productsize')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prodoct_Colors', to='product.productcolor')),
            ],
        ),
    ]
