# Generated by Django 4.2.7 on 2024-06-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_color_siz'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_color_siz',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
