# Generated by Django 4.2.7 on 2024-06-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productcolorsize_delete_product_color_siz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSizePointer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('sizes', models.ManyToManyField(to='product.size')),
            ],
        ),
    ]
