# Generated by Django 4.2.7 on 2024-06-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_colorsizepointer_quantities'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorsizepointer',
            name='j',
            field=models.JSONField(default=list),
        ),
    ]
