# Generated by Django 4.2.7 on 2024-06-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_colorsizepointer_j'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorsizepointer',
            name='j',
        ),
        migrations.AlterField(
            model_name='colorsizepointer',
            name='quantities',
            field=models.JSONField(default=list),
        ),
    ]
