# Generated by Django 4.2.7 on 2024-07-30 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_colorsizepointer_j_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSearchLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
                ('search_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.searchlabel')),
            ],
        ),
    ]
