# Generated by Django 4.2.7 on 2024-08-06 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_searchlabel_productsearchlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'BrandModel',
                'verbose_name_plural': 'BrandModels',
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='search_labls',
            field=models.ManyToManyField(related_name='product_label', through='product.ProductSearchLabel', to='product.searchlabel'),
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brandmodel')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='mark',
            field=models.ManyToManyField(related_name='product_mark', through='product.ProductBrand', to='product.brandmodel'),
        ),
    ]
