# Generated by Django 4.2.7 on 2024-08-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_brandmodel_productmodel_search_labls_productbrand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='reviews',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
