# Generated by Django 4.2.7 on 2024-08-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_parent_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='replies_data',
            field=models.ManyToManyField(related_name='replies', to='reviews.reply'),
        ),
    ]
