# Generated by Django 4.2.7 on 2024-08-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_replies_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='banneduser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
