# Generated by Django 4.2.7 on 2024-08-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_banneduser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banneduser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='reply',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
