# Generated by Django 4.2.7 on 2024-08-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_banneduser_is_active_reply_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='banneduser',
            name='unbanned',
            field=models.BooleanField(default=False),
        ),
    ]
