# Generated by Django 4.2.7 on 2024-08-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_nonregesteredclient_is_active'),
        ('reviews', '0006_banneduser_unbanned'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedNonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('unbanned', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banned_user', to='client.nonregesteredclient')),
            ],
        ),
    ]
