# Generated by Django 4.2.7 on 2024-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionmodel',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
