# Generated by Django 4.2.7 on 2024-06-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_promotionmodel_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
