# Generated by Django 4.2.7 on 2024-06-03 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_userprofile_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='promo_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='used',
        ),
        migrations.CreateModel(
            name='UserPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.promotionmodel')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='promo_codes',
            field=models.ManyToManyField(through='Shop.UserPromoCode', to='Shop.promotionmodel'),
        ),
    ]
