# Generated by Django 4.2.7 on 2024-06-11 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('headline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertizmentheadline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertizmentheadline',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertizmentheadline',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='advertizement_shop/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertizmentheadline',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertizmentheadline',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertizmentheadline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
