# Generated by Django 4.2.7 on 2024-06-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headline', '0002_advertizmentheadline_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertizmentheadline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertizement_shop/'),
        ),
    ]
