# Generated by Django 4.2.7 on 2024-07-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headline', '0003_alter_advertizmentheadline_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertizmentheadline',
            name='for_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertizmentheadline',
            name='product',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
