# Generated by Django 4.2.7 on 2024-06-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_color_siz'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='cart.CartItem', to='product.productcolor'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcolor'),
        ),
        migrations.AlterField(
            model_name='temprarycart',
            name='products',
            field=models.ManyToManyField(through='cart.TempraryCartCartItem', to='product.productcolor'),
        ),
        migrations.AlterField(
            model_name='temprarycartcartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcolor'),
        ),
    ]
