# Generated by Django 4.2.7 on 2024-06-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productcolorsize_delete_product_color_siz'),
        ('cart', '0003_alter_cart_products_alter_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcolorsize'),
            preserve_default=False,
        ),
    ]
