# Generated by Django 4.2.7 on 2024-08-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_wishlist_wishlistitem_wishlist_product_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temprarycartcartitem',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
