# Generated by Django 4.2.7 on 2024-08-22 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_fabricmodel_productfabric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_nonregestredorder_nonregestredorderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_order_id', models.IntegerField()),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CancelledOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_cancellation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancelled_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cancelledorder')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productmodel')),
            ],
        ),
        migrations.AddField(
            model_name='cancelledorder',
            name='products',
            field=models.ManyToManyField(through='order.CancelledOrderItem', to='product.productmodel'),
        ),
        migrations.AddField(
            model_name='cancelledorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
