# Generated by Django 4.2.7 on 2024-08-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cancelledorder_cancelledorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonregestredorder',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
