# Generated by Django 4.2.7 on 2024-08-22 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_nonregestredorder_is_canceled_order_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledorder',
            name='original_order_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
