# Generated by Django 4.2.7 on 2024-08-22 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_fabricmodel_productfabric'),
        ('client', '0004_alter_client_email'),
        ('order', '0005_cancelledorder_original_order_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledNonOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_order_id', models.IntegerField()),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('original_order_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.nonregestredorder')),
            ],
        ),
        migrations.CreateModel(
            name='CancelledNonOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_cancellation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancelled_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cancellednonorder')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productmodel')),
            ],
        ),
        migrations.AddField(
            model_name='cancellednonorder',
            name='products',
            field=models.ManyToManyField(through='order.CancelledNonOrderItem', to='product.productmodel'),
        ),
        migrations.AddField(
            model_name='cancellednonorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.nonregesteredclient'),
        ),
    ]
