# Generated by Django 4.2.7 on 2024-08-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_cancellednonorder_cancellednonorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledorder',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
