# Generated by Django 4.2.7 on 2024-08-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_cancelledorder_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellednonorder',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
