# Generated by Django 4.2.7 on 2024-08-28 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0006_client_user'),
        ('product', '0016_fabricmodel_productfabric'),
        ('order', '0008_cancellednonorder_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_delivery_time', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidNonOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('shipping_info', models.TextField(blank=True, null=True)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ValidOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('shipping_info', models.TextField(blank=True, null=True)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='cancellednonorderitem',
            name='sutotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cancelledorderitem',
            name='sutotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nonregestredorder',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nonregestredorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='nonregestredorder',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nonregestredorderitem',
            name='sutotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sutotal',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ValidOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_validation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sutotal', models.IntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productmodel')),
                ('validated_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.validorder')),
            ],
        ),
        migrations.AddField(
            model_name='validorder',
            name='original_order_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='validorder',
            name='products',
            field=models.ManyToManyField(through='order.ValidOrderItem', to='product.productmodel'),
        ),
        migrations.AddField(
            model_name='validorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ValidNonOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_validation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sutotal', models.IntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productmodel')),
                ('validated_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.validnonorder')),
            ],
        ),
        migrations.AddField(
            model_name='validnonorder',
            name='original_order_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.nonregestredorder'),
        ),
        migrations.AddField(
            model_name='validnonorder',
            name='products',
            field=models.ManyToManyField(through='order.ValidNonOrderItem', to='product.productmodel'),
        ),
        migrations.AddField(
            model_name='validnonorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.nonregesteredclient'),
        ),
        migrations.CreateModel(
            name='ShippingNonAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state_or_region', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='client.nonregesteredclient')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state_or_region', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='client.client')),
            ],
        ),
        migrations.AddField(
            model_name='nonregestredorder',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.shippingnonaddress'),
        ),
        migrations.AddField(
            model_name='nonregestredorder',
            name='shipping_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.shippingmethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.shippingaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.shippingmethod'),
        ),
    ]
